language: python

sudo: false

addons:
  apt:
    packages:
      - poppler-utils
      - imagemagick

python:
  - '3.3'
  - '3.4'
  - '3.5'

install:
  - pip install tox-travis

script:
  - tox

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cccb04073ce95d678fd3
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
