language: python

sudo: false

cache:
    apt: true
    directories:
      - $HOME/.cache/pip

matrix:
  include:
    - python: '3.3'
    - python: '3.4'
    - python: '3.5'
      addons:
        apt:
          packages:
            - poppler-utils
            - imagemagick
    - python: 'nightly'
    - python: 'pypy3.3-5.2-alpha1'

install:
  - pip install tox-travis wheel
  - python setup.py bdist_wheel

script:
  - travis_wait 45 tox
  - travis_wait 45 tox --installpkg ./dist/rinohtype-*.whl

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cccb04073ce95d678fd3
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
