language: python

sudo: false

cache:
    apt: true
    directories:
      - $HOME/.cache/pip

python:
  - 3.3
  - 3.4
  - 3.5
  - nightly
  - pypy3.3-5.2-alpha1

env:
  - DIST=
    WITH_COVERAGE=1
  - DIST="--installpkg ./dist/rinohtype-*.whl"

matrix:
  include:
    - python: 3.5
      env: TOXENV=check
    - python: 3.5
      env:
        - TOXENV=regression
        - TIMEOUT=travis_wait 45
        - WITH_COVERAGE=1
      addons:
        apt:
          packages:
            - poppler-utils
            - imagemagick
    - python: 3.5
      env: TOXENV=test-docs

install:
  - pip install tox-travis wheel
  - python setup.py bdist_wheel

script:
  - $TIMEOUT tox -v $DIST

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cccb04073ce95d678fd3
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
