language: python

sudo: false

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y poppler-utils imagemagick

python:
  - '3.3'
  - '3.4'
  - '3.5'

install:
  - pip install tox-travis

script:
  - tox
